import type { User, PackageRequest, WalletTransaction } from './types';

export const mockUsers: User[] = [
  {
    id: 'user1',
    name: 'Alice Sender',
    email: 'alice@example.com',
    avatarUrl: 'https://placehold.co/100x100.png',
    type: 'Sender',
    walletBalance: 150.75,
    createdAt: new Date('2023-01-15T09:00:00Z'),
  },
  {
    id: 'user2',
    name: 'Bob Traveler',
    email: 'bob@example.com',
    avatarUrl: 'https://placehold.co/100x100.png',
    type: 'Traveler',
    walletBalance: 320.50,
    createdAt: new Date('2023-02-20T14:30:00Z'),
  },
  {
    id: 'user3',
    name: 'Charlie Both',
    email: 'charlie@example.com',
    avatarUrl: 'https://placehold.co/100x100.png',
    type: 'Sender', // Can be both, but primary role set here
    walletBalance: 50.00,
    createdAt: new Date('2023-03-10T11:20:00Z'),
  },
];

export const mockPackageRequests: PackageRequest[] = [
  {
    id: 'pkg1',
    senderId: 'user1',
    senderName: 'Alice Sender',
    originCity: 'New York',
    destinationCity: 'Los Angeles',
    size: 'Medium',
    weight: 5,
    proposedPrice: 25,
    status: 'Posted',
    trackingId: 'SWFT000001',
    imageUrl: 'https://placehold.co/600x400.png',
    description: 'Urgent documents in a medium-sized envelope.',
    createdAt: new Date('2024-07-20T10:00:00Z'),
    updatedAt: new Date('2024-07-20T10:00:00Z'),
  },
  {
    id: 'pkg2',
    senderId: 'user3',
    senderName: 'Charlie Both',
    originCity: 'Chicago',
    destinationCity: 'Houston',
    size: 'Small',
    weight: 1.5,
    proposedPrice: 15,
    status: 'Accepted',
    travelerId: 'user2',
    travelerName: 'Bob Traveler',
    trackingId: 'SWFT000002',
    imageUrl: 'https://placehold.co/600x400.png',
    description: 'A small gift box for a friend.',
    createdAt: new Date('2024-07-18T14:30:00Z'),
    updatedAt: new Date('2024-07-19T09:15:00Z'),
  },
  {
    id: 'pkg3',
    senderId: 'user1',
    senderName: 'Alice Sender',
    originCity: 'San Francisco',
    destinationCity: 'Seattle',
    size: 'Large',
    weight: 12,
    proposedPrice: 40,
    status: 'Negotiating',
    trackingId: 'SWFT000003',
    imageUrl: 'https://placehold.co/600x400.png',
    description: 'Box of books and clothes.',
    createdAt: new Date('2024-07-21T08:00:00Z'),
    updatedAt: new Date('2024-07-21T11:00:00Z'),
    negotiation: {
      originalPrice: 40,
      currentPrice: 35,
      lastOfferBy: 'traveler',
      offers: [
        { userId: 'user1', userName: 'Alice Sender', price: 40, timestamp: new Date('2024-07-21T08:00:00Z'), type: 'sender' },
        { userId: 'user2', userName: 'Bob Traveler', price: 35, timestamp: new Date('2024-07-21T11:00:00Z'), type: 'traveler' },
      ]
    }
  },
  {
    id: 'pkg4',
    senderId: 'user3',
    senderName: 'Charlie Both',
    originCity: 'Miami',
    destinationCity: 'New York',
    size: 'Medium',
    weight: 3,
    proposedPrice: 20,
    status: 'En Route',
    travelerId: 'user2',
    travelerName: 'Bob Traveler',
    trackingId: 'SWFT000004',
    imageUrl: 'https://placehold.co/600x400.png',
    description: 'Electronics, handle with care.',
    createdAt: new Date('2024-07-15T12:00:00Z'),
    updatedAt: new Date('2024-07-16T18:00:00Z'),
  },
    {
    id: 'pkg5',
    senderId: 'user1',
    senderName: 'Alice Sender',
    originCity: 'Boston',
    destinationCity: 'Los Angeles',
    size: 'Small',
    weight: 0.5,
    proposedPrice: 10,
    status: 'Posted',
    trackingId: 'SWFT000005',
    imageUrl: 'https://placehold.co/600x400.png',
    description: 'Important letter.',
    createdAt: new Date('2024-07-22T09:30:00Z'),
    updatedAt: new Date('2024-07-22T09:30:00Z'),
  },
];

export const mockWalletTransactions: WalletTransaction[] = [
  {
    id: 'txn1',
    userId: 'user1',
    type: 'Deposit',
    amount: 100,
    description: 'Initial account funding',
    timestamp: new Date('2023-01-15T09:05:00Z'),
    status: 'Completed',
  },
  {
    id: 'txn2',
    userId: 'user1',
    type: 'PaymentSent',
    amount: 25,
    description: 'Payment for package SWFT000001',
    relatedPackageId: 'pkg1',
    relatedUserId: 'user2',
    timestamp: new Date('2024-07-20T11:00:00Z'),
    status: 'Completed',
  },
  {
    id: 'txn3',
    userId: 'user2',
    type: 'PaymentReceived',
    amount: 25,
    description: 'Received payment for package SWFT000001 delivery',
    relatedPackageId: 'pkg1',
    relatedUserId: 'user1',
    timestamp: new Date('2024-07-20T11:05:00Z'),
    status: 'Completed',
  },
  {
    id: 'txn4',
    userId: 'user2',
    type: 'Withdrawal',
    amount: 50,
    description: 'Withdrawal to bank account',
    timestamp: new Date('2024-07-21T15:00:00Z'),
    status: 'Pending',
  },
];
